modLoader="javafml"
loaderVersion="[47,)"
license="GNU Lesser General Public License version 2.1 (LGPLv2.1)"

[[mods]]
modId="simply_home"
version="1.0.3"
displayName="Simply Home"
credits="Azureddraig"
displayURL="https://discord.gg/GTgx6tYjg2"
authors="Azureddraig"
description="A simple home warp crystal mod with cooldowns that persist"

[[dependencies.simply_home]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




